django_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('contacts/', views.flatpage, {'url': '/contacts/'}, name='contacts'),
    path('contact/', include('contact.urls')),
    path('', include('movies.urls')),
    # path('i18n/', include('django.conf.urls.i18n')),
]
    # path('pages/', include('django.contrib.flatpages.urls')),
# urlpatterns += i18n_patterns(
  
# )


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
	path('', views.MoviesView.as_view(), name='main'),
	path("filter/", views.FilterMoviesView.as_view(), name='filter'),
	path("search/", views.Search.as_view(), name='search'),
	path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),
	path("json-filter/", views.JsonFilterMoviesView.as_view(), name='json_filter'),
	path("<slug:slug>/", views.MovieDetailView.as_view(), name='movie_detail'),
	path("review/<int:pk>/", views.AddReview.as_view(), name='add_review'),
	path("actor/<str:slug>/", views.ActorView.as_view(), name='actor_detail'),
]

movies/models.py
from django.db import models
from datetime import date
from django.urls import reverse
# Create your models here.

class Category(models.Model):
	""" Categories """
	name = models.CharField("Category", max_length=150)
	description = models.TextField("Description")
	url = models.SlugField(max_length=160, unique=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name='Category'
		verbose_name_plural='Categories'

class Actor(models.Model):
	""" Actors and directors """
	name = models.CharField("Name", max_length=100)
	age = models.PositiveSmallIntegerField("Age", default=0)
	description = models.TextField("Description")
	image = models.ImageField("Image", upload_to="actors/")

	def get_absolute_url(self):
		return reverse("actor_detail", kwargs={'slug':self.name})

	def __str__(self):
		return self.name

	class Meta:
		verbose_name='Actors and directors'
		verbose_name_plural='Actors and directors'

class Genre(models.Model):
	""" Genres """
	name = models.CharField("Genre", max_length=100)
	description = models.TextField("Description")
	url = models.SlugField(max_length=160, unique=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name ='Genre'
		verbose_name_plural ='Genres'

class Movie(models.Model):
	""" Movie """
	title = models.CharField("Title", max_length=100)
	tagline = models.CharField("Tagline", max_length=100, default='')
	description = models.TextField("Description")
	poster = models.ImageField("Poster", upload_to="movies/")
	year = models.PositiveSmallIntegerField("Release year",default=2020)
	country = models.CharField("Country", max_length=30)
	directors = models.ManyToManyField(Actor,verbose_name='Directors', related_name='film_director')
	actors = models.ManyToManyField(Actor, verbose_name='Actors', related_name='film_actor')
	genres = models.ManyToManyField(Genre, verbose_name='Genres')
	world_premiere = models.DateField("World premiere", default=date.today)
	budget = models.PositiveSmallIntegerField("Budget", default=0, help_text='Enter price in dollars')
	fees_in_usa = models.PositiveSmallIntegerField("Fees in USA",
		default=0, help_text='Enter price in dollars')
	fees_in_world = models.PositiveSmallIntegerField("Fees in the World",
		default=0, help_text='Enter price in dollars')
	category = models.ForeignKey(Category, verbose_name='Category', on_delete=models.SET_NULL, null=True)
	url = models.SlugField(max_length=160, unique=True)
	draft = models.BooleanField("Draft",default=False)

	def get_absolute_url(self):
		return reverse('movie_detail', kwargs={'slug':self.url})

	def get_review(self):
		return self.reviews_set.filter(parent__isnull=True)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name='Movie'
		verbose_name_plural='Movies'

class MovieShots(models.Model):
	""" Shots from movie """
	title = models.CharField("Title", max_length=100)
	description = models.TextField("Description")
	image = models.ImageField("Image", upload_to="movie_shots/")
	movie = models.ForeignKey(Movie, verbose_name='Movie', on_delete=models.CASCADE)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name='Shots from movie'
		verbose_name_plural='Shots from movies'

class RatingStar(models.Model):
	""" Rating star """
	value = models.SmallIntegerField("Value",default=0)

	def __str__(self):
		return f'{self.value}'

	class Meta:
		verbose_name='Rating star'
		verbose_name_plural='Rating stars'
		ordering = ["-value"]

class Rating(models.Model):
	""" Rating """
	ip = models.CharField("IP adress", max_length=15)
	star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name='star')
	movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='movie')

	def __str__(self):
		return f"{self.star} - {self.movie}"

	class Meta:
		verbose_name='Rating'
		verbose_name_plural='Ratings'

class Reviews(models.Model):
	""" Reviews """
	email = models.EmailField()
	name = models.CharField("Name", max_length=100)
	text = models.TextField("Message", max_length=5000)
	parent = models.ForeignKey('self', verbose_name='parent',
		on_delete=models.SET_NULL, blank=True, null=True)
	movie = models.ForeignKey(Movie, verbose_name='movie', on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.name} - {self.movie}"

	class Meta:
		verbose_name='Review'
		verbose_name_plural='Reviews'

movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField


from .models import Reviews, Rating, RatingStar

class ReviewForm(forms.ModelForm):
	"""Review form"""
	
	captcha = ReCaptchaField()

	class Meta:
		model = Reviews
		fields = ('name','email','text','captcha')
		widgets = {
			"name":forms.TextInput(attrs={"class":"form-control border"}),
			"email":forms.EmailInput(attrs={"class":"form-control border"}),
			"text":forms.Textarea(attrs={"class":"form-control border"})
		}


class RatingForm(forms.ModelForm):
	""" Form to add rating """
	star = forms.ModelChoiceField(
			queryset = RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
		)

	class Meta:
		model = Rating
		fields = ("star",)

movies/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.conf import settings
# Create your views here.

from .models import Movie, Category, Actor, Genre, Rating, Reviews
from .forms import ReviewForm, RatingForm

class GenreYear:
	""" Genre and year released """
	def get_genres(self):
		return Genre.objects.all().order_by("name")

	def get_years(self):
		return Movie.objects.filter(draft=False).order_by("year").values("year")


class MoviesView(GenreYear, ListView):
	""" List of movies """
	model = Movie
	queryset = Movie.objects.filter(draft=False)
	# template_name = 'movies/movie_list.html'
	paginate_by = 3


class MovieDetailView(GenreYear, DetailView):
	"""Full description of the movie"""
	model = Movie
	slug_field = 'url'
	# template_name = 'movies/movie_detail.html'

	def get_user_stars(self, ip, movie_id):
	    if Rating.objects.filter(ip=ip, movie_id=movie_id).exists():
	    	stars = Rating.objects.get(ip=ip, movie_id=movie_id).star
	    else:
	    	stars = None
	    return stars

	def get(self, request, *args, **kwargs):
		ip = AddStarRating.get_client_ip(self, self.request)
		movie_id = Movie.objects.get(url=kwargs['slug']).id
		stars = self.get_user_stars(ip, movie_id)
		self.object = self.get_object()
		context = self.get_context_data(object=self.request)
		if stars:
			context['stars'] = str(stars)
		return self.render_to_response(context)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context["star_form"] = RatingForm()
		context["form"] = ReviewForm()
		return context


class AddReview(View):
	""" Reviews """
	def post(self,request,pk):
		form = ReviewForm(request.POST)
		movie = Movie.objects.get(id=pk)
		if form.is_valid():
			form = form.save(commit=False)
			if request.POST.get("parent", None):
				form.parent_id = int(request.POST.get("parent"))
			form.movie = movie
			form.save() 
		return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
	""" Information about actors """
	model = Actor
	template_name = "movies/actor.html"
	slug_field = "name"


class FilterMoviesView(GenreYear, ListView):
	""" Movies filter """
	paginate_by = 2

	def get_queryset(self):
		queryset = Movie.objects.filter(
			Q(year__in = self.request.GET.getlist("year")) |
			Q(genres__in = self.request.GET.getlist("genre"))
		).distinct()
		return queryset

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
		context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
		return context

class JsonFilterMoviesView(ListView):
	""" Movies filter in json """
	def get_queryset(self):
		queryset = Movie.objects.filter(
			Q(year__in = self.request.GET.getlist("year")) |
			Q(genres__in = self.request.GET.getlist("genre"))
		).distinct().values('title','tagline','url','poster')
		return queryset

	def get(self, request, *args, **kwargs):
		queryset = list(self.get_queryset())
		return JsonResponse({'movies':queryset}, safe=False)


class AddStarRating(View):
    """Add rating to movie"""
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

class Search(GenreYear, ListView):
	"""Search movie"""

	paginate_by = 3

	def get_queryset(self):
		return Movie.objects.filter(title__icontains=self.request.GET.get("q"))

	def get_context_data(self,*args,**kwargs):
	    context = super().get_context_data(*args,**kwargs)
	    context["q"] = f'{self.request.GET.get("q")}&'
	    return context

django_movie/templates/movies/actor.html
{% extends "movies/base.html" %}

{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
 {% block container %}
     <div class="container py-md-3">
{% endblock container %}

 {% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-6">
            <img src="{{ actor.image.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent" style="outline: none; cursor: inherit;">
                {{ movie.title }}
            </h3>
            <h5 class="editContent"></h5>
            <ul>
                <li>
                    <span><b>Age:</b> {{ actor.age }} years</span></li>
                <li>
                    <span><b>Director in:</b>
                        {% for movie in actor.film_director.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                </li>
                <li><span><b>Actor in:</b>
                    {% for movie in actor.film_actor.all %}
                        {{ movie.title }}
                    {% endfor %}
                </span>
                </li>
            </ul>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">

        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            About {{ actor.name }}
        </h3>
        <p class="editContent" style="outline: none; cursor: inherit;">
            {{ actor.description|safe }}
        </p>
       <!--  <p class="mt-3 italic-blue editContent"
           style="outline: none; cursor: inherit;">
            <iframe width="560" height="315"
                    src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                    frameborder="0" allow="accelerometer; autoplay;
                    encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
            </iframe>
        </p> -->
    </div>
</div>
{% endblock movie %}

django_movie/templates/movies/base.html
{% extends "base.html" %}

{% block content %}

	 <section class="ab-info-main py-md-5 py-4 editContent"
	 		style="padding-left: 3rem; padding-right: 3rem;">
	    
	    {% block container %}	
	    <div class="container-fluid py-md-3">
	    {% endblock container %}
	    
        <div class="row">

	        {% block sidebar %}
	        	<div class="side-bar col-lg-3">
	        {% endblock sidebar %}
	        {% include "include/sidebar.html" %}
			</div>

			{% block movie %}
				
			{% endblock movie %}

		</div>
		</div>
	</section>
		
{% endblock content %}

django_movie/templates/movies/movie_detail.html
{% extends "movies/base.html" %}

{% load static %}
{% block title %} {{ movie.title }} {% endblock title %}
 {% block container %}
     <div class="container py-md-3">
{% endblock container %}

 {% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-6">
            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent" style="outline: none; cursor: inherit;">
                {{ movie.title }}
            </h3>
            <h5 class="editContent"></h5>
            <ul>
                <li style="list-style: none">
                    <span><b>Year:</b> {{ movie.year }}</span></li>
                <li style="list-style: none">
                    <span><b>Country:</b> {{ movie.country }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Tagline:</b> {{ movie.tagline }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Director:</b>
                        {% for director in movie.directors.all %}
                           <a href="{{ director.get_absolute_url }}">
                                {{ director.name }}
                            </a>
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none"><span><b>Actors:</b>
                    {% for actor in movie.actors.all %}
                      <a href="{{ actor.get_absolute_url }}">
                            {{ actor.name }}
                        </a>
                    {% endfor %}
                </span>
                </li>
                <li style="list-style: none"><span><b>Genre:</b>
                    {% for genre in movie.genres.all %}
                        {{ genre.name }}
                    {% endfor %}
                    </span>
                </li>
                <li><span><b>Worl premiere:</b> {{ movie.world_premiere }}</span></li>
                <li><span><b>Budget:</b> ${{ movie.budget }}</span></li>
                <li><span><b>Fees in USA:</b> ${{ movie.fees_in_usa }}</span></li>
                <li><span><b>Fees in the world:</b> ${{ movie.fees_in_world }}</span></li>
                <li>
                    <form action="{% url 'add_rating' %}" method="post" name="rating">
                        <b>Rating:</b>
                        {% csrf_token %}
                        <input type="hidden" value="{{ movie.id }}" name="movie">
                        <span class="rating">
                            {% for k,v in star_form.fields.star.choices %}
                                <input id="rating{{ v }}" type="radio" {% if stars == v %}checked{% endif %} name="star" value="{{ k }}">
                                <label for="rating{{ v }}">{{ k }}</label>
                            {% endfor %}
                        </span>
                        <span class="editContent">4.0</span>
                    </form>
                </li>
                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent"
                            style="outline: none; cursor: inherit;">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-facebook-f"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-twitter"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-dribbble"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">

        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            About movie {{ movie.title }}
        </h3>
        <p>
            {% for image in movie.movieshots_set.all %}
                <img src="{{ image.image.url }}" class="img-movie-shots" alt="{{ image.description }}"> 
            {% endfor %}
        </p>
        <p class="editContent" style="outline: none; cursor: inherit;">
            {{ movie.description|safe }}
        </p>
       <!--  <p class="mt-3 italic-blue editContent"
           style="outline: none; cursor: inherit;">
            <iframe width="560" height="315"
                    src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                    frameborder="0" allow="accelerometer; autoplay;
                    encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
            </iframe>
        </p> -->
    </div>
    <hr>
    <div class="row">
        <div class="single-form-left">
            <!-- contact form grid -->
            <div class="contact-single">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    <span class="sub-tittle editContent"
                          style="outline: none; cursor: inherit;">{{ movie.reviews_set.count }}</span>Leave
                    comment</h3>
                <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                    {% csrf_token %}
                    <input type="hidden" name="parent" id="contactparent" value="">
                    <div class="form-group editContent">
                        <label for="contactcomment" class="editContent">
                            Your comment *
                        </label>
                        {{ form.text }}
                    </div>
                    <div class="d-sm-flex">
                        <div class="col-sm-6 form-group p-0 editContent">
                            <label for="contactusername" class="editContent">
                               Name *
                           </label>
                           {{ form.name }}
                        </div>
                        <div class="col-sm-6 form-group ml-sm-3 editContent">
                            <label for="contactemail" class="editContent">
                               Email *
                           </label>
                            {{ form.email }}
                        </div>
                        {{ form.captcha }}
                    </div>
                    <button type="submit"
                            class="mt-3 btn btn-success btn-block py-3">
                            Send
                    </button>
                </form>
            </div>
            <!--  //contact form grid ends here -->
        </div>
    {% for review in movie.get_review %}
        <div class="media py-5">
            <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
            <div class="media-body mt-4">
                <h5 class="mt-0 editContent">{{ review.name }}</h5>
                <p class="mt-2 editContent">{{ review.text }}</p>
                <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Reply to comment</a>
                {% for rev in review.reviews_set.all %}
                    <div class="media mt-5 editContent">
                        <img src="{% static 'images/te1.jpg' %}" class="img-fluid" alt="image">
                        <div class="media-body">
                            <h5 class="mt-0 editContent">{{ rev.name }}</h5>
                            <p class="mt-2 editContent">{{ rev.text }}</p>
                        </div> 
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %} 
    </div>
</div>

<script type="text/javascript">
    function addReview(name,id){
        document.getElementById("contactparent").value = id;
        document.getElementById("contactcomment").innerText = `${name}, `
    }
</script>

{% endblock movie %}

django_movie/templates/movies/movie_list.html
{% extends "movies/base.html" %}

{% block title %} Main {% endblock title %}
{% block header %}bg1{% endblock header %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4" >
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="" >
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent" >
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent" >{{ movie.tagline}}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="grid-img-right mt-4 text-right bg bg1" >
            {% include "include/pagination.html" %}
        </div>
    </div>

{% endblock movie %}

django_movie/templates/movies/movies.html
{% extends "movies/base.html" %}

{% block title %} Main {% endblock title %}
{% block header %}bg1{% endblock header %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4" >
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid" alt="" >
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}" class="editContent" >
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent" >{{ movie.tagline}}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star-half-o" aria-hidden="true" ></span></a></li>
                                <li><a href="#"><span class="fa fa-star-o" aria-hidden="true" ></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <!--<div class="grid-img-right mt-4 text-right bg bg1" >
            <span class="money editContent" >Flat 50% Off</span>
            <a href="moviesingle.html" class="btn" >Now</a>
        </div>-->
    </div>

{% endblock movie %}